import type {
  User,
  Tenant,
  SecurityIncident,
  NetworkDevice,
  DashboardMetrics,
  AuditLogEntry,
  FirewallRule,
  NetworkConnection,
  NetworkTopology,
  NetworkSubnet,
} from "@/types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@acmecorp.com",
    name: "John Smith",
    role: "admin",
    tenantId: "tenant-1",
    avatar: "/professional-avatar.png",
    lastLogin: new Date(),
    isActive: true,
  },
  {
    id: "2",
    email: "sarah.analyst@acmecorp.com",
    name: "Sarah Johnson",
    role: "analyst",
    tenantId: "tenant-1",
    avatar: "/professional-woman-analyst.jpg",
    lastLogin: new Date(Date.now() - 3600000), // 1 hour ago
    isActive: true,
  },
  {
    id: "3",
    email: "mike.auditor@acmecorp.com",
    name: "Mike Chen",
    role: "auditor",
    tenantId: "tenant-1",
    avatar: "/professional-man-auditor.jpg",
    lastLogin: new Date(Date.now() - 86400000), // 1 day ago
    isActive: true,
  },
  {
    id: "4",
    email: "lisa.security@acmecorp.com",
    name: "Lisa Rodriguez",
    role: "analyst",
    tenantId: "tenant-1",
    avatar: "/professional-woman-security.jpg",
    lastLogin: new Date(Date.now() - 7200000), // 2 hours ago
    isActive: false,
  },
  {
    id: "5",
    email: "david.admin@acmecorp.com",
    name: "David Wilson",
    role: "admin",
    tenantId: "tenant-1",
    avatar: "/professional-man-admin.jpg",
    lastLogin: new Date(Date.now() - 1800000), // 30 minutes ago
    isActive: true,
  },
]

export const mockTenant: Tenant = {
  id: "tenant-1",
  name: "ACME Corporation",
  domain: "acmecorp.com",
  plan: "enterprise",
  createdAt: new Date("2024-01-15"),
  isActive: true,
  settings: {
    ssoEnabled: true,
    ssoProvider: "azure",
    maxUsers: 100,
    retentionDays: 365,
    alertsEnabled: true,
  },
}

export const mockIncidents: SecurityIncident[] = [
  {
    id: "inc-1",
    title: "Suspicious Login Attempts",
    severity: "high",
    status: "investigating",
    description:
      "Multiple failed login attempts detected from unusual IP addresses. The attempts originated from several different geographic locations within a short time frame, suggesting a coordinated attack.",
    detectedAt: new Date("2024-12-09T10:30:00"),
    assignedTo: "2",
    tags: ["authentication", "brute-force", "login"],
    affectedAssets: ["web-server-01", "auth-service", "load-balancer-01"],
  },
  {
    id: "inc-2",
    title: "Malware Detection",
    severity: "critical",
    status: "open",
    description:
      "Trojan detected on workstation in finance department. The malware appears to be attempting to access financial databases and may have already exfiltrated sensitive data.",
    detectedAt: new Date("2024-12-09T14:15:00"),
    tags: ["malware", "endpoint", "trojan", "finance"],
    affectedAssets: ["ws-finance-05", "file-server-02"],
  },
  {
    id: "inc-3",
    title: "DDoS Attack Detected",
    severity: "high",
    status: "resolved",
    description:
      "Distributed denial of service attack targeting our main web servers. Attack was successfully mitigated using rate limiting and traffic filtering.",
    detectedAt: new Date("2024-12-08T16:45:00"),
    resolvedAt: new Date("2024-12-08T18:30:00"),
    assignedTo: "5",
    tags: ["ddos", "network", "web-server"],
    affectedAssets: ["web-server-01", "web-server-02", "load-balancer-01"],
  },
  {
    id: "inc-4",
    title: "Unauthorized Access Attempt",
    severity: "medium",
    status: "investigating",
    description:
      "Attempted unauthorized access to administrative panel detected. User account has been temporarily suspended pending investigation.",
    detectedAt: new Date("2024-12-09T09:15:00"),
    assignedTo: "5",
    tags: ["access-control", "admin-panel", "unauthorized"],
    affectedAssets: ["admin-server-01"],
  },
  {
    id: "inc-5",
    title: "Data Exfiltration Alert",
    severity: "critical",
    status: "open",
    description:
      "Unusual data transfer patterns detected suggesting potential data exfiltration. Large volumes of sensitive data accessed outside normal business hours.",
    detectedAt: new Date("2024-12-09T02:30:00"),
    tags: ["data-exfiltration", "insider-threat", "database"],
    affectedAssets: ["database-server-01", "backup-server-01"],
  },
  {
    id: "inc-6",
    title: "Phishing Campaign Detected",
    severity: "medium",
    status: "closed",
    description:
      "Phishing emails targeting employees detected and blocked. All affected users have been notified and security awareness training scheduled.",
    detectedAt: new Date("2024-12-07T11:20:00"),
    resolvedAt: new Date("2024-12-07T15:45:00"),
    assignedTo: "2",
    tags: ["phishing", "email", "social-engineering"],
    affectedAssets: ["email-server-01"],
  },
]

export const mockDevices: NetworkDevice[] = [
  {
    id: "fw-001",
    name: "Main Firewall",
    type: "firewall",
    ip: "192.168.1.1",
    location: "Data Center A",
    status: "online",
    lastSeen: new Date(),
    firmwareVersion: "9.1.4",
    coordinates: { x: 400, y: 200 },
    connections: ["sw-001", "rt-001"],
    ports: [
      { id: "fw-001-p1", name: "GE0/0", type: "ethernet", status: "up", speed: "1Gbps", connectedTo: "sw-001" },
      { id: "fw-001-p2", name: "GE0/1", type: "ethernet", status: "up", speed: "1Gbps", connectedTo: "rt-001" },
    ],
    metrics: { cpuUsage: 45, memoryUsage: 62, bandwidth: 850, uptime: 99.9, temperature: 42 },
  },
  {
    id: "sw-001",
    name: "Core Switch",
    type: "switch",
    ip: "192.168.1.10",
    location: "Data Center A",
    status: "online",
    lastSeen: new Date(),
    coordinates: { x: 200, y: 300 },
    connections: ["fw-001", "sv-001", "sv-002"],
    ports: [
      { id: "sw-001-p1", name: "Port 1", type: "ethernet", status: "up", speed: "1Gbps", connectedTo: "fw-001" },
      { id: "sw-001-p2", name: "Port 2", type: "ethernet", status: "up", speed: "1Gbps", connectedTo: "sv-001" },
      { id: "sw-001-p3", name: "Port 3", type: "ethernet", status: "up", speed: "1Gbps", connectedTo: "sv-002" },
    ],
    metrics: { cpuUsage: 25, memoryUsage: 38, bandwidth: 1200, uptime: 99.8 },
  },
  {
    id: "fw-002",
    name: "Branch Firewall",
    type: "firewall",
    ip: "10.0.1.1",
    location: "Branch Office",
    status: "warning",
    lastSeen: new Date(Date.now() - 300000),
    firmwareVersion: "9.0.2",
    coordinates: { x: 600, y: 100 },
    connections: ["rt-001"],
    ports: [
      { id: "fw-002-p1", name: "GE0/0", type: "ethernet", status: "up", speed: "100Mbps", connectedTo: "rt-001" },
    ],
    metrics: { cpuUsage: 78, memoryUsage: 85, bandwidth: 95, uptime: 98.2, temperature: 55 },
  },
  {
    id: "rt-001",
    name: "Core Router",
    type: "router",
    ip: "192.168.1.254",
    location: "Data Center A",
    status: "online",
    lastSeen: new Date(),
    coordinates: { x: 400, y: 50 },
    connections: ["fw-001", "fw-002", "internet"],
    ports: [
      { id: "rt-001-p1", name: "GE0/0", type: "ethernet", status: "up", speed: "10Gbps", connectedTo: "fw-001" },
      { id: "rt-001-p2", name: "GE0/1", type: "fiber", status: "up", speed: "1Gbps", connectedTo: "fw-002" },
      { id: "rt-001-p3", name: "WAN", type: "fiber", status: "up", speed: "1Gbps", connectedTo: "internet" },
    ],
    metrics: { cpuUsage: 35, memoryUsage: 45, bandwidth: 2400, uptime: 99.95 },
  },
  {
    id: "sv-001",
    name: "Web Server",
    type: "server",
    ip: "192.168.1.100",
    location: "Data Center A",
    status: "online",
    lastSeen: new Date(),
    coordinates: { x: 100, y: 400 },
    connections: ["sw-001"],
    ports: [{ id: "sv-001-p1", name: "eth0", type: "ethernet", status: "up", speed: "1Gbps", connectedTo: "sw-001" }],
    metrics: { cpuUsage: 65, memoryUsage: 72, bandwidth: 450, uptime: 99.7, temperature: 38 },
  },
  {
    id: "sv-002",
    name: "Database Server",
    type: "server",
    ip: "192.168.1.101",
    location: "Data Center A",
    status: "online",
    lastSeen: new Date(),
    coordinates: { x: 300, y: 400 },
    connections: ["sw-001"],
    ports: [{ id: "sv-002-p1", name: "eth0", type: "ethernet", status: "up", speed: "1Gbps", connectedTo: "sw-001" }],
    metrics: { cpuUsage: 55, memoryUsage: 68, bandwidth: 320, uptime: 99.9, temperature: 41 },
  },
]

export const mockConnections: NetworkConnection[] = [
  {
    id: "conn-1",
    sourceDeviceId: "fw-001",
    targetDeviceId: "sw-001",
    sourcePort: "GE0/0",
    targetPort: "Port 1",
    connectionType: "ethernet",
    bandwidth: "1Gbps",
    status: "active",
  },
  {
    id: "conn-2",
    sourceDeviceId: "fw-001",
    targetDeviceId: "rt-001",
    sourcePort: "GE0/1",
    targetPort: "GE0/0",
    connectionType: "ethernet",
    bandwidth: "10Gbps",
    status: "active",
  },
  {
    id: "conn-3",
    sourceDeviceId: "rt-001",
    targetDeviceId: "fw-002",
    sourcePort: "GE0/1",
    targetPort: "GE0/0",
    connectionType: "fiber",
    bandwidth: "1Gbps",
    status: "active",
  },
  {
    id: "conn-4",
    sourceDeviceId: "sw-001",
    targetDeviceId: "sv-001",
    sourcePort: "Port 2",
    targetPort: "eth0",
    connectionType: "ethernet",
    bandwidth: "1Gbps",
    status: "active",
  },
  {
    id: "conn-5",
    sourceDeviceId: "sw-001",
    targetDeviceId: "sv-002",
    sourcePort: "Port 3",
    targetPort: "eth0",
    connectionType: "ethernet",
    bandwidth: "1Gbps",
    status: "active",
  },
]

export const mockSubnets: NetworkSubnet[] = [
  {
    id: "subnet-1",
    name: "DMZ",
    cidr: "192.168.1.0/24",
    vlan: 100,
    deviceIds: ["fw-001", "sw-001", "sv-001", "sv-002", "rt-001"],
    color: "#3b82f6",
  },
  {
    id: "subnet-2",
    name: "Branch Network",
    cidr: "10.0.1.0/24",
    vlan: 200,
    deviceIds: ["fw-002"],
    color: "#10b981",
  },
]

export const mockTopology: NetworkTopology = {
  devices: mockDevices,
  connections: mockConnections,
  subnets: mockSubnets,
}

export const mockMetrics: DashboardMetrics = {
  attacksBlocked: 1247,
  trafficVolume: 2.4, // TB
  anomaliesDetected: 23,
  activeThreats: 5,
  systemHealth: 98.5,
  connectedDevices: 156,
}

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: "log-1",
    timestamp: new Date("2024-12-09T15:30:00"),
    userId: "1",
    action: "firewall_rule_created",
    resource: "firewall_rules",
    details: { ruleName: "Block Suspicious IPs", ruleId: "rule-123" },
    ip: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    severity: "info",
  },
  {
    id: "log-2",
    timestamp: new Date("2024-12-09T15:25:00"),
    userId: "2",
    action: "incident_status_changed",
    resource: "incidents",
    details: { incidentId: "inc-1", oldStatus: "open", newStatus: "investigating" },
    ip: "192.168.1.101",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    severity: "info",
  },
  {
    id: "log-3",
    timestamp: new Date("2024-12-09T14:45:00"),
    userId: "1",
    action: "user_created",
    resource: "users",
    details: { userName: "Lisa Rodriguez", userId: "4", role: "analyst" },
    ip: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    severity: "info",
  },
  {
    id: "log-4",
    timestamp: new Date("2024-12-09T14:20:00"),
    userId: "3",
    action: "login_failed",
    resource: "authentication",
    details: { email: "unknown@example.com", reason: "invalid_credentials" },
    ip: "203.0.113.45",
    userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36",
    severity: "warning",
  },
  {
    id: "log-5",
    timestamp: new Date("2024-12-09T13:55:00"),
    userId: "2",
    action: "network_device_status_changed",
    resource: "network_devices",
    details: { deviceId: "fw-002", deviceName: "Branch Firewall", oldStatus: "online", newStatus: "warning" },
    ip: "192.168.1.101",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    severity: "warning",
  },
  {
    id: "log-6",
    timestamp: new Date("2024-12-09T13:30:00"),
    userId: "1",
    action: "firewall_rule_deleted",
    resource: "firewall_rules",
    details: { ruleName: "Temporary Allow Rule", ruleId: "rule-temp-001" },
    ip: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    severity: "warning",
  },
  {
    id: "log-7",
    timestamp: new Date("2024-12-09T12:15:00"),
    userId: "5",
    action: "user_login",
    resource: "authentication",
    details: { loginMethod: "sso", provider: "azure" },
    ip: "192.168.1.105",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    severity: "info",
  },
  {
    id: "log-8",
    timestamp: new Date("2024-12-09T11:45:00"),
    userId: "2",
    action: "incident_created",
    resource: "incidents",
    details: { incidentId: "inc-7", title: "Unusual Network Traffic", severity: "medium" },
    ip: "192.168.1.101",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
    severity: "info",
  },
  {
    id: "log-9",
    timestamp: new Date("2024-12-09T11:20:00"),
    userId: "1",
    action: "system_backup_completed",
    resource: "system",
    details: { backupSize: "2.4GB", duration: "45 minutes", location: "backup-server-01" },
    ip: "192.168.1.100",
    userAgent: "System/Automated",
    severity: "info",
  },
  {
    id: "log-10",
    timestamp: new Date("2024-12-09T10:30:00"),
    userId: "unknown",
    action: "unauthorized_access_attempt",
    resource: "authentication",
    details: { targetResource: "admin_panel", blockedBy: "firewall_rule_001" },
    ip: "203.0.113.89",
    userAgent: "curl/7.68.0",
    severity: "error",
  },
  {
    id: "log-11",
    timestamp: new Date("2024-12-09T09:45:00"),
    userId: "3",
    action: "audit_export_generated",
    resource: "audit_logs",
    details: { exportFormat: "csv", dateRange: "2024-12-01 to 2024-12-08", recordCount: 1247 },
    ip: "192.168.1.103",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    severity: "info",
  },
  {
    id: "log-12",
    timestamp: new Date("2024-12-09T09:15:00"),
    userId: "1",
    action: "tenant_settings_updated",
    resource: "tenants",
    details: { tenantId: "tenant-1", changes: ["retentionDays: 365 -> 730", "maxUsers: 100 -> 150"] },
    ip: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    severity: "info",
  },
]

export const mockFirewallRules: FirewallRule[] = [
  {
    id: "rule-1",
    name: "Allow HTTP Traffic",
    action: "allow",
    source: "any",
    destination: "192.168.1.0/24",
    port: "80",
    protocol: "tcp",
    enabled: true,
    priority: 100,
    createdAt: new Date("2024-12-01"),
    modifiedAt: new Date("2024-12-01"),
    version: 1,
  },
  {
    id: "rule-2",
    name: "Block Malicious IPs",
    action: "deny",
    source: "203.0.113.0/24",
    destination: "any",
    port: "any",
    protocol: "any",
    enabled: true,
    priority: 1,
    createdAt: new Date("2024-12-09"),
    modifiedAt: new Date("2024-12-09"),
    version: 1,
  },
]
